DROP TABLE IF EXISTS users1 CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS each_user_answers CASCADE;

CREATE TABLE users1 (
  id SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_ID INTEGER REFERENCES users1(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  isListed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_ID INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  answer VARCHAR(255) NOT NULL,
  isCorrect BOOLEAN NOT NULL
);

CREATE TABLE each_user_answers (
  id SERIAL PRIMARY KEY NOT NULL,
  user_ID INTEGER REFERENCES users1(id) ON DELETE CASCADE,
  answer_id INTEGER REFERENCES answers(id) ON DELETE CASCADE
);

